# Generated by Django 5.2.15 on 2026-06-28 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovado', models.BooleanField(default=False)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('serie', models.CharField(choices=[('9EF', '9º ano EF'), ('1EM', '1ª série EM'), ('2EM', '2ª série EM'), ('3EM', '3ª série EM'), ('4EM', '4ª série EM')], max_length=3)),
                ('escola', models.CharField(max_length=200)),
                ('tipo_escola', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('SELETIVA', 'Seletiva')], max_length=8)),
                ('professor_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('professor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo', models.CharField(blank=True, max_length=7, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
