# Generated by Django 5.2.16 on 2026-07-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_ajusta_manager_e_tipo_usuario'),
        ('contas', '0003_alter_usuario_managers_alter_usuario_tipo'),
    ]

    operations = [
    ]
