# Generated by Django 5.2.16 on 2026-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_merge_20260730_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('ADM', 'Administrador')], default='ADM', max_length=5),
        ),
    ]
